### ISSUE TITLE
AMD Documentation lists incorrect GitHub page for source code.

### ISSUE THREAD

**Issue by tygoetsch** [amd/aocl-sparse#3]
As the title suggests, https://www.amd.com/en/developer/aocl/scalapack.html lists the old repo https://github.com/amd/scalapack for the source code for this project.

**Comment by pradeeptrgit** [comment]
@tygoetsch Thank you for pointing out the incorrect link for aocl-scalapack source. We will fix that. But this is aocl-sparse forum. Next time you can log issue on scalapack in the https://github.com/amd/aocl-scalapack/issues. I saw that "Issues" tab was not enabled for aocl-scalapack repository. Its now enabled.

**Comment by tygoetsch** [comment]
Thank you! Sorry, I think Github must have auto-selected a repo when I created a new issue.

**Comment by pradeeptrgit** [comment]
@tygoetsch the link for aocl-scalapack is now fixed with correct URL.
