### ISSUE TITLE
Any plans to parallelize aoclsparse_csrmm?

### ISSUE THREAD

**Issue by omidasudeh** [amd/aocl-sparse#6]
I was just running the documented benchmarks for csrmv and csrmm and realized that csrmm is not responsive to changes to number of threads (while csrmv was); Then looking into the [code](https://github.com/amd/aocl-sparse/blob/master/library/src/level3/aoclsparse_csrmm.hpp) to me there is no parallel code section (e.g. #pragma omp parallel). So was wondering if you have any plans to parallelize AOCL SpMM. Attached is the runs I did. 
![Screenshot 2024-07-03 at 5 52 41 PM](https://github.com/amd/aocl-sparse/assets/13192254/5cd8f214-e234-4fec-86cd-88f15f7cfe38)

Thanks,

**Comment by vchunchu-amd** [comment]
We do have plans to support multi-threaded csrmm/spmm and will be available in future

**Comment by vchunchu-amd** [comment]
@midasudeh: Pls use latest code from dev branch for CSRMM multi threading support.
